"""B4 - Data-quality report -> reports/data_quality_report.md (+ CSV of the missing-value decisions).

Extends the Session 2 column survey (does not repeat it): handling decision per
missing column, label-consistency checks, shortcut cross-tabs and the list of
columns that must never be model inputs.
"""
import _bootstrap  # noqa: F401
from milk10k_pipeline import config, data, quality
from milk10k_pipeline.reporting import df_to_markdown


def main() -> None:
    config.ensure_output_dirs()
    images = data.load_images_table()
    gt = data.load_gt()
    md = ["# MILK10k - data-quality report (Milestone 1, B4)\n",
          f"Generated by `scripts/04_quality_report.py` from {len(images)} metadata rows.\n"]

    # 1. missing values
    miss = quality.missing_table(images)
    miss.to_csv(config.OUTPUT_DIR / "missing_value_decisions.csv")
    md += ["## 1. Columns with missing values and handling decision\n", df_to_markdown(miss, index=True), ""]

    # 2. label consistency
    per_lesion = quality.images_per_lesion_check(images)
    onehot = gt.drop(columns=["lesion_id", "dx"]).sum(axis=1)
    disagree = quality.lesion_fields_consistency(images)
    h32 = quality.hierarchy_violations(images, "diagnosis_3", "diagnosis_2")
    h21 = quality.hierarchy_violations(images, "diagnosis_2", "diagnosis_1")
    checks = [
        ("lesion_id sets identical in metadata and ground truth", set(images.lesion_id) == set(gt.lesion_id)),
        ("every lesion has exactly ONE positive class", bool((onehot == 1).all())),
        ("exactly 2 images per lesion", per_lesion["lesions_not_2_images"] == 0),
        ("one dermoscopic + one clinical image per lesion", per_lesion["lesions_wrong_type_pair"] == 0),
        ("both images agree on age/sex/site/diagnosis_1-4", int(disagree.sum()) == 0),
        ("diagnosis_3 -> exactly one diagnosis_2", h32.empty),
        ("diagnosis_2 -> exactly one diagnosis_1", h21.empty),
    ]
    md += ["## 2. Label-consistency checks\n",
           "| check | result |", "|---|---|"]
    md += [f"| {name} | {'PASS' if ok else 'FAIL'} |" for name, ok in checks]
    c2d = quality.class_to_diagnosis1(images)
    md += ["", "11-class label vs diagnosis_1 (lesions). **AKIEC maps to two diagnosis_1 values**, "
           "so diagnosis_1 cannot be derived from an 11-class prediction:\n",
           df_to_markdown(c2d, index=True), ""]

    # 3. shortcuts
    md += ["## 3. Shortcut check (images, row %)\n"]
    for col, tab in quality.shortcut_crosstabs(images).items():
        md += [f"**{col} x diagnosis_1**\n", df_to_markdown(tab, index=True), ""]
    md += ["**Conclusion.** `image_type` is perfectly balanced (each lesion has both views), so it carries no "
           "label information and is safe to use. `image_manipulation == altered` is strongly enriched in "
           "Indeterminate lesions (about 13% vs 2%), so it is a potential shortcut: it is not given to the model "
           "and later results will also be reported on unaltered images only. `diagnosis_confirm_type` "
           "separates Benign from Malignant almost perfectly because it records whether a biopsy was done, i.e. "
           "a decision taken *after* a clinician suspected malignancy - a textbook label leak.\n"]

    # 4. leaky columns
    md += ["## 4. Columns NOT used as model inputs\n", df_to_markdown(quality.leaky_columns_table()), ""]
    md += ["Allowed inputs: the images; optionally `age_approx`, `sex`, `anatom_site_general` "
           "(with 'unknown') as metadata, evaluated separately.\n"]

    out = config.REPORT_DIR / "data_quality_report.md"
    out.write_text("\n".join(md))
    print("\n".join(md))
    print(f"\nsaved {out.relative_to(config.REPO_ROOT)}")


if __name__ == "__main__":
    main()
